import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import * as nodemailer from 'nodemailer';
import SMTPTransport from 'nodemailer/lib/smtp-transport';

@Injectable()
export class NotificationService implements OnModuleInit {
  private readonly logger = new Logger(NotificationService.name);
  private transport: nodemailer.Transporter;

  onModuleInit() {
    this.transport = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    this.transport.verify((error) => {
      if (error) {
        this.logger.error('SMTP Connection Failed:', error);
      } else {
        this.logger.log('SMTP Server Connected Successfully. Mailer Ready.');
      }
    });
  }

  async sendFailureAlert(
    monitorId: string,
    url: string,
    statusCode: number | null,
    errorMessage: string | null,
  ) {
    const subject = `🚨 CRITICAL ALERT: Monitor for ${url} is DOWN!`;
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ffcccc; background-color: #fff5f5; border-radius: 8px;">
        <h2 style="color: #cc0000; margin-bottom: 5px;">🔴 Incident Detected</h2>
        <p style="font-size: 16px; color: #333;">Your managed service endpoint has stopped responding normally.</p>
        <hr style="border: 0; border-top: 1px solid #ffcccc; margin: 15px 0;" />
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td><strong>Target URL:</strong></td><td><a href="${url}">${url}</a></td></tr>
          <tr><td><strong>HTTP Status:</strong></td><td><span style="background:#ffdddd; padding:2px 6px; border-radius:4px; color:#cc0000; font-weight:bold;">${statusCode || 'N/A'}</span></td></tr>
          <tr><td><strong>Error Root Cause:</strong></td><td><code style="background:#eee; padding:2px 5px; border-radius:4px;">${errorMessage || 'Unknown Network Error'}</code></td></tr>
          <tr><td><strong>Timestamp:</strong></td><td>${new Date().toISOString()}</td></tr>
        </table>
        <div style="margin-top: 20px; font-size: 12px; color: #777;">This is an automated operational alert generated by Uptime Shield.</div>
      </div>
    `;

    await this.executeMailDispatch(subject, htmlContent);
  }

  async sendRecoveryAlert(monitorId: string, url: string) {
    const subject = `✅ RECOVERY: Monitor for ${url} is back UP!`;
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #cceecc; background-color: #f5fff5; border-radius: 8px;">
        <h2 style="color: #008800; margin-bottom: 5px;">🟢 Incident Resolved</h2>
        <p style="font-size: 16px; color: #333;">Great news! The target endpoint has recovered and is now stable.</p>
        <hr style="border: 0; border-top: 1px solid #cceecc; margin: 15px 0;" />
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td><strong>Target URL:</strong></td><td><a href="${url}">${url}</a></td></tr>
          <tr><td><strong>Current State:</strong></td><td><span style="background:#ddffdd; padding:2px 6px; border-radius:4px; color:#008800; font-weight:bold;">UP & STABLE</span></td></tr>
          <tr><td><strong>Resolved At:</strong></td><td>${new Date().toISOString()}</td></tr>
        </table>
        <div style="margin-top: 20px; font-size: 12px; color: #777;">Monitoring operations have resumed normal observation.</div>
      </div>
    `;

    await this.executeMailDispatch(subject, htmlContent);
  }

  private async executeMailDispatch(subject: string, html: string) {
    try {
      const info = (await this.transport.sendMail({
        from: process.env.SMTP_FROM,
        to: 'admin@yourcompany.com',
        subject: subject,
        html: html,
      })) as SMTPTransport.SentMessageInfo;
      this.logger.log(
        `Email dispatched successfully. MessageID: ${info.messageId}`,
      );
      const previewUrl = nodemailer.getTestMessageUrl(info);
      if (previewUrl) {
        this.logger.verbose(`View Outgoing Email Preview: ${previewUrl}`);
      }
    } catch (error) {
      this.logger.error(
        'Failed to dispatch notification email via SMTP:',
        error,
      );
    }
  }
}
